version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install gcc
          command: apt-get update && apt-get install gcc
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: compile
          command: gcc main.c -o main
